#!/bin/ksh
# /etc/rc.d/juicefs - OpenBSD rc.d script for JuiceFS mount
# Logs go to syslog (LOG_USER facility) → /var/log/messages by default
# To route to a separate file, add to /etc/syslog.conf:
#   user.info  /var/log/juicefs.log

daemon="/usr/local/bin/juicefs"
daemon_flags="mount"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_start() {
  . /etc/juicefs/juicefs.env
  export JUICEFS_META_URL JUICEFS_MOUNT_POINT
  : ${JUICEFS_MOUNT_POINT:=/mnt/juicefs}
  mkdir -p "$JUICEFS_MOUNT_POINT"
  # Remove stale graceful-upgrade sockets to avoid 10s timeout
  rm -f /tmp/fuse_fd_comm.*
  # Run with -d (background/daemon mode) which enables syslog logging
  ${daemon} mount -d "$JUICEFS_META_URL" "$JUICEFS_MOUNT_POINT"
}

rc_stop() {
  pkill -f "juicefs mount"
}

rc_check() {
  pgrep -q -f "juicefs mount"
}

rc_cmd $1
